module.exports = {
  type: 'widget',
  name: 'LivraWidget',
  bundleIdentifier: 'com.livra.app.widget',
  deploymentTarget: '16.0',
  frameworks: ['SwiftUI', 'WidgetKit', 'AppIntents'],
  entitlements: {
    'com.apple.security.application-groups': ['group.com.livra.app'],
  },
  // The app's real Phosphor duotone glyphs - one imageset per glyph, COLOURLESS
  // (the duotone ratio lives in the alpha channel). LivraWidget.swift tints them
  // at runtime with .renderingMode(.template) plus the accent carried in the
  // snapshot, so a mark wears its OWN glyph in its OWN hue here exactly as it
  // does in the app.
  //
  // GENERATED - do not hand-edit. Run scripts/generate-widget-icons.js to write
  // the PNGs, then regenerate this list; tests/unit/widgetIcons.test.ts fails if
  // this list and the manifest disagree.
  images: {
    livra_barbell: './icons/barbell.png',
    livra_bicycle: './icons/bicycle.png',
    livra_book_open: './icons/book_open.png',
    livra_book_open_text: './icons/book_open_text.png',
    livra_bowl_food: './icons/bowl_food.png',
    livra_brain: './icons/brain.png',
    livra_briefcase: './icons/briefcase.png',
    livra_cake: './icons/cake.png',
    livra_calendar: './icons/calendar.png',
    livra_calendar_check: './icons/calendar_check.png',
    livra_cigarette: './icons/cigarette.png',
    livra_circle: './icons/circle.png',
    livra_coffee: './icons/coffee.png',
    livra_cooking_pot: './icons/cooking_pot.png',
    livra_currency_circle_dollar: './icons/currency_circle_dollar.png',
    livra_currency_dollar: './icons/currency_dollar.png',
    livra_drop: './icons/drop.png',
    livra_envelope_simple: './icons/envelope_simple.png',
    livra_fire: './icons/fire.png',
    livra_footprints: './icons/footprints.png',
    livra_fork_knife: './icons/fork_knife.png',
    livra_globe_simple: './icons/globe_simple.png',
    livra_graduation_cap: './icons/graduation_cap.png',
    livra_hand_heart: './icons/hand_heart.png',
    livra_handshake: './icons/handshake.png',
    livra_heart: './icons/heart.png',
    livra_hourglass: './icons/hourglass.png',
    livra_house: './icons/house.png',
    livra_metronome: './icons/metronome.png',
    livra_monitor: './icons/monitor.png',
    livra_moon: './icons/moon.png',
    livra_moon_stars: './icons/moon_stars.png',
    livra_note_pencil: './icons/note_pencil.png',
    livra_paint_brush: './icons/paint_brush.png',
    livra_pen_nib: './icons/pen_nib.png',
    livra_pencil_simple: './icons/pencil_simple.png',
    livra_person_simple: './icons/person_simple.png',
    livra_person_simple_run: './icons/person_simple_run.png',
    livra_piggy_bank: './icons/piggy_bank.png',
    livra_prohibit: './icons/prohibit.png',
    livra_pulse: './icons/pulse.png',
    livra_shield: './icons/shield.png',
    livra_shower: './icons/shower.png',
    livra_sparkle: './icons/sparkle.png',
    livra_target: './icons/target.png',
    livra_trend_up: './icons/trend_up.png',
    livra_users: './icons/users.png',
    livra_users_three: './icons/users_three.png',
    livra_wallet: './icons/wallet.png',
    livra_waves: './icons/waves.png',
    livra_wind: './icons/wind.png',
  },
};
